apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.container.image }}
        ports:
        - containerPort: {{ .Values.container.port }}
        resources:
          requests:
            cpu: {{ .Values.cpu.request }}
          limits:
            cpu: {{ .Values.cpu.limit }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.service.label }}
spec:
  ports:
  - port: {{ .Values.service.port }}
  selector:
    app: {{ .Values.service.selector }}