apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.hpa.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  minReplicas: {{ .Values.hpa.replica.min }}
  maxReplicas:  {{ .Values.hpa.replica.max }}
  metrics:
  - type: Resource
    resource:
      name: {{ .Values.hpa.resource.type }}
      target:
        type: Utilization
        averageUtilization:  {{ .Values.hpa.average.utilization }}
