apiVersion: v1
kind: Pod
metadata:
  name: load-generator
spec:
  containers:
  - name: {{ .Values.load.name }}
    image:  {{ .Values.load.image }}
    command: [{{ .Values.load.bash }}, {{ .Values.load.args }}, {{ .Values.load.script }}]
  restartPolicy: {{ .Values.load.restart_policy }}